import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = { docs: [{ type: 'autogenerated', dirName: '.' }] };  // key must be "docs" (navbar sidebarId)
export default sidebars;
